actors:
  saekisy:
    image_url: /images/actors/saekisy.jpg
    name: saekisy
    url: https://twitter.com/saekisy
  furu8ma:
    image_url: /images/actors/furu8ma.jpeg
    name: furu8ma
    url: https://github.com/furu8ma
author: furu8ma
description: young engineer and old engineer discuss about tech and etc..
description_long: 人生これからな若手エンジニアと、エンジニア定年年齢を大幅に超えたおっさんエンジニアがキャリアやテックについてあれこれ話すPodcast
email: furu8ma@gmail.com
exclude:
  - docker
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE.txt
  - README.md
  - vendor
hashtag: wakateossan
itunes_podcast_url: https://itunes.apple.com/jp/podcast/%E8%8B%A5%E6%89%8B%E3%81%A8%E3%81%8A%E3%81%A3%E3%81%95%E3%82%93/id1355585949
keywords: tech,technology,programming,mobile,web,development,developer,software,minor
language: ja
markdown: kramdown
permalink: /episode/:title
sass:
  sass_dir: css
timezone: Asia/Tokyo
title: 若手とおっさん
url: https://wakate-ossan.github.io
google_analytics: UA-2849270-4
